version: '3'
services:
  zoo1:
    image: zookeeper:3.6
    container_name: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181

  solr1:
    image: solr:latest
    container_name: solr1
    ports:
      - "8983:8983"
    environment:
      - ZK_HOST=zoo1:2181
    command:
      - solr-foreground
      - -c
      - -z
      - zoo1:2181
    depends_on:
      - zoo1
    volumes:
      - ./data/solr1:/var/solr