create table REVIEW_TABLE (
    id bigint generated by default as identity,
    createDate timestamp(6),
    updateDate timestamp(6),
    COMMENT varchar(255),
    DELIVERY_SCORE integer check ((DELIVERY_SCORE<=5) and (DELIVERY_SCORE>=1)),
    FOOD_SCORE integer check ((FOOD_SCORE<=5) and (FOOD_SCORE>=1)),
    PRESENTATION_SCORE integer check ((PRESENTATION_SCORE<=5) and (PRESENTATION_SCORE>=1)),
    RESTAURANT_ID varchar(255),
    REVIEW_DATE date,
    user_id bigint,
    primary key (id)
);

create table USER_TABLE
(
    id         bigint generated by default as identity,
    createDate timestamp(6),
    updateDate timestamp(6),
    E_MAIL     varchar(255),
    FIRST_NAME varchar(100) not null,
    LAST_NAME  varchar(100) not null,
    LATITUDE   float(53)    not null,
    LONGITUDE  float(53)    not null,
    PASSWORD   varchar(400) not null,
    TELEPHONE  varchar(255),
    primary key (id)
);